kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    type: hostPath
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/redis"
